In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape

(3,)

In [6]:
y = range(10)

In [7]:
y

range(0, 10)

In [8]:
y = np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
y = np.arange(10)

In [10]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [12]:
x + y

array([3., 6., 9.])

In [13]:
x * y

array([ 2.,  8., 18.])

In [14]:
x / 2.0

array([0.5, 1. , 1.5])

In [15]:
A = np.array([[1, 2], [3, 4]])

In [16]:
print(A)

[[1 2]
 [3 4]]


In [17]:
A.shape

(2, 2)

In [18]:
A.dtype

dtype('int64')

In [20]:
B = np.array([[3.0, 0.6]])

In [21]:
print(A+B)

[[4.  2.6]
 [6.  4.6]]


In [22]:
print(A*B)

[[3.  1.2]
 [9.  2.4]]
